# Generated by Django 5.2.3 on 2025-06-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('main_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default="Don't Miss!", max_length=50)),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('feature1', models.CharField(max_length=100)),
                ('feature2', models.CharField(max_length=100)),
                ('feature3', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_promo_images/')),
                ('read_blog_url', models.URLField(default='#')),
                ('view_all_blogs_url', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(blank=True, max_length=254, null=True)),
                ('resume_link', models.URLField(blank=True, help_text='Link to your downloadable resume', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('responsibilities', models.JSONField(help_text='Enter responsibilities as a JSON array of strings.')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=200)),
                ('main_heading', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('fluid_image', models.ImageField(blank=True, null=True, upload_to='hero_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_heading_part1', models.CharField(max_length=200)),
                ('intro_heading_part2', models.CharField(max_length=200)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="A short label for the skill, used in CSS classes (e.g., 'skill-python')", unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Home.aboutsection')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Home.servicesection')),
            ],
        ),
    ]
