# Generated by Django 5.2.3 on 2025-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client.', max_length=100)),
                ('client_title', models.CharField(blank=True, help_text="e.g., 'CEO of XYZ Corp', 'Marketing Manager'", max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company the client works for (optional).', max_length=150, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Optional: LinkedIn profile URL for verification.', null=True)),
                ('testimonial_text', models.TextField(help_text='The actual testimonial message.')),
                ('client_image', models.ImageField(blank=True, help_text='Optional: Upload your photo (e.g., headshot).', null=True, upload_to='testimonials/client_images/')),
                ('company_logo', models.ImageField(blank=True, help_text='Optional: Upload your company logo.', null=True, upload_to='testimonials/company_logos/')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text="Client's rating (1-5 stars).")),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials will be shown on the website.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Testimonial',
                'verbose_name_plural': 'Client Testimonials',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
