# Generated by Django 5.2.3 on 2025-06-11 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default="Don't Miss!", max_length=50)),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('feature1', models.CharField(max_length=100)),
                ('feature2', models.CharField(max_length=100)),
                ('feature3', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_promo_images/')),
                ('read_blog_url', models.URLField(default='#')),
                ('view_all_blogs_url', models.URLField(default="{% url 'blogs' %}")),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPromotion',
        ),
    ]
