# Generated by Django 5.2.3 on 2025-06-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_blog_delete_blogpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_all_blogs_url',
            field=models.TextField(default="{% url 'blogs' %}"),
        ),
    ]
