# Generated by Django 5.2.3 on 2025-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_blog_view_all_blogs_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='fluid_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
